import React from "react";
import styled from "styled-components";
import { Flex, Text, Button } from "../components/Base";
import { AiOutlineHome } from "react-icons/ai";
import Link from "next/link";
import titleBar from "../assets/titlebar-bg.jpg";
import Head from "next/head";
import Image from "next/image";
import antDTabs from "antd/lib/tabs";
import generator1 from "../assets/generators/generator6.jpg";
import generator2 from "../assets/generators/generator5.jpg";
import generator3 from "../assets/generators/generator2.png";
import generator4 from "../assets/generators/generator3.jpg";
import generator5 from "../assets/generators/generator4.jpeg";
import generator6 from "../assets/generators/generator16.jpg";
import generator7 from "../assets/generators/generator15.jpg";
import generator8 from "../assets/generators/generator14.jpg";
import generator9 from "../assets/generators/generator13.jpg";
import generator10 from "../assets/generators/generator12.jpg";
import generator11 from "../assets/generators/generator11.jpg";
import generator12 from "../assets/generators/generator10.jpg";
import generator13 from "../assets/generators/generator1.jpg";
import generator14 from "../assets/generators/rental.jpg";
import switchGear1 from "../assets/generators/generator21.jpg";
import switchGear2 from "../assets/generators/generator20.jpg";
import switchGear3 from "../assets/generators/generator19.jpg";
import switchGear4 from "../assets/generators/generator18.jpg";
import switchGear5 from "../assets/generators/generator17.jpg";
import sparePart1 from "../assets/generators/generator7.jpg";
import sparePart2 from "../assets/generators/generator8.jpg";
import sparePart3 from "../assets/generators/generator9.jpg";

const Tabs = styled(antDTabs)`
display: flex !important;
align-items: center !important;
justify-content: center !important;
  .ant-tabs-tab {
    width: 250px;
    height: 80px;
    display: flex !important;
    font-size: 1.2rem;
    align-items: center !important;
    justify-content: center !important;
    color: rgba(0, 48, 100, 1) !important;
    &:hover {
      background: rgb(255, 199, 44) !important;
      color: #fff !important;
    }
    @media (max-width: 1000px) {
      width: 70px;
      height: 40px;
      font-size: 0.6rem;
    }
  }
  .ant-tabs-tab-active {
    background: rgb(255, 199, 44) !important;
    color: #fff !important;
  }
  .ant-tabs-tab.ant-tabs-tab-active .ant-tabs-tab-btn {
    color: #fff !important;
  }
  &.ant-tabs-top > .ant-tabs-nav .ant-tabs-ink-bar,
  .ant-tabs-top > div > .ant-tabs-nav .ant-tabs-ink-bar {
    display: none !important;
  }
`;
const StyledDiv = styled.div`
  background-image: url(${titleBar.src});
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  height: 13rem;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  color: #fff;
  text-align: center;
`;
const TabContainer = styled.div`
  background-color: #fff;
  width: 100%;
  padding: 1rem;
`;
const ImageWrapper = styled.div`
  display: flex;
  flex-wrap: wrap;
  gap: 1rem;
`;
const FooterHeader = styled.div`
  height: 30rem;
  @media (max-width: 768px) {
    height: 52rem;
  }
`;
export default function gallery() {
  const GeneratorImages = [
    generator1,
    generator2,
    generator3,
    generator4,
    generator5,
    generator6,
    generator7,
    generator8,
    generator9,
    generator10,
    generator11,
    generator12,
    generator13,
    generator14,
  ];
  const SwitchGearImages = [
    switchGear1,
    switchGear2,
    switchGear3,
    switchGear4,
    switchGear5,
  ];
  const SparePartImages = [sparePart1, sparePart2, sparePart3];
  return (
    <>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledDiv>
        <Flex direction="column">
          <Text
            width="100%"
            mobileWidth="100%"
            fontSize="2rem"
            color="#fff"
            textAlign="center"
            fontWeight="bold"
            mobileTextAlign="center"
            mobileFontSize="2rem"
          >
            Gallery
          </Text>
          <Flex width="100%" justifyContent="center" gap="0px">
            <Flex width="20%" directionMobile="row" widthMobile="40%" gap="0px">
              <Link href="/">
                <Flex
                  width="50%"
                  justifyContent="center"
                  directionMobile="row"
                  widthMobile="40%"
                >
                  {" "}
                  <AiOutlineHome style={{ fontSize: "1.5rem" }} />
                  <Text
                    color="#fff"
                    fontSize="1rem"
                    textAlign="center"
                    fontWeight="bold"
                    cursor="pointer"
                    width="40%"
                  >
                    Home
                  </Text>
                </Flex>
              </Link>
              /
              <Flex width="40%" directionMobile="row" widthMobile="40%">
                <Text
                  fontSize="1rem"
                  color="rgb(255, 199, 44)"
                  textAlign="center"
                  fontWeight="bold"
                  cursor="pointer"
                >
                  Gallery
                </Text>{" "}
              </Flex>
            </Flex>
          </Flex>
        </Flex>
      </StyledDiv>
      <TabContainer>
        <Flex direction="column" alignItems="center" justifyContent="center">
          <Text textAlign="center" fontSize="1rem" color="rgb(136,142,148)">
            Gallery
          </Text>
          <Text
            textAlign="center"
            fontWeight="bold"
            color="rgb(1,44,90)"
            fontSize="1.5rem"
          >
            {" "}
            Nileco Electric Equipment Manufacturing PLC
          </Text>
        </Flex>
        <Flex justifyContent="center">
          <Tabs defaultActiveKey="1">
            <Tabs.TabPane tab=" Generator" key="1">
              <ImageWrapper style={{marginLeft:"2rem"}}>
                {GeneratorImages.map((image) => (
                  <Image src={image.src} width="300px" height="300px" />
                ))}
              </ImageWrapper>
            </Tabs.TabPane>
            <Tabs.TabPane tab="Switch Gears" key="2">
            <ImageWrapper style={{marginLeft:"2rem"}}>
                {SwitchGearImages.map((image) => (
                  <Image src={image.src} width="300px" height="300px" />
                ))}
              </ImageWrapper>
            </Tabs.TabPane>
            <Tabs.TabPane tab="Spare Parts" key="3">
            <ImageWrapper style={{marginLeft:"2rem"}}>
                {SparePartImages.map((image) => (
                  <Image src={image.src} width="300px" height="300px" />
                ))}
              </ImageWrapper>
            </Tabs.TabPane>
            <Tabs.TabPane tab="Events" key="4">
              Events
            </Tabs.TabPane>
          </Tabs>
        </Flex>
      </TabContainer>
      <FooterHeader></FooterHeader>
    </>
  );
}
