import styles from "../styles/Home.module.css";
import Head from "next/head";
import NavBar from "../components/navbar";
import styled from "styled-components";
import Button from "antd/lib/button";
import Image from "next/image";
import volva from '../assets/vol.jpg';
const HeaderContainer = styled.div``;




const Text = styled.h1`
font-size:${(props)=>props.fontSize || '15px'};
color:${(props)=>props.color || '#000000'};
font-weight:${(props)=>props.fontWeight || '#000000'};
`;
export default function Home() {
  return (
    <>
      <Head>
        <title>Nilec</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <HeaderContainer className={styles.Section}>
        <div className={styles.SectionVertical}>
          <Text fontSize={"14px"} color="yellow">--Welcome to Nileco--</Text>
          <Text fontSize={"50px"} color="blue">We are leader in power and technology</Text>
          <Text fontSize={"18px"} color="white">We offer the most reliable power services in the country</Text>
          <div className={styles.SectionHorizontal}>
            <Button> About Us</Button>
            <Button> Contact Us</Button>
          </div>
        </div>
      </HeaderContainer>
      <div className={styles.whiteSection}>
<Image src={volva}/>
      </div>
    </>
  );
}
