import Head from "next/head";
import Layout from "antd/lib/layout/layout";
import NavBar from "../components/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nilec</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </>
  );
}
